# Generated by Django 4.0.6 on 2022-10-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=5)),
                ('email_id', models.EmailField(max_length=20)),
                ('company_code', models.CharField(max_length=5)),
                ('created_time', models.TimeField()),
            ],
        ),
    ]
